// SPDX-License-Identifier: MIT
pragma solidity 0.8.36;

/// @title IDefiSimplify7702Account
/// @notice Frozen v1 ABI for checkpoint-based dynamic account execution and one authenticated Aave V3 callback.
/// @dev Token addresses are supplied by the plan and trusted to implement ERC20
///      `balanceOf(address)` semantics. The account accepts a successful balance read
///      with at least 32 bytes and interprets its first word as the unsigned balance.
interface IDefiSimplify7702Account {
    /// @notice Selects the token-balance base used to resolve a calldata patch.
    enum BalanceSource {
        /// @notice Uses the delegated account's entire current token balance.
        CurrentBalance,
        /// @notice Uses only the balance increase since a named checkpoint.
        CheckpointDelta
    }

    /// @notice Describes an ERC20 balance snapshot created before a target call.
    /// @param token ERC20 whose delegated-account balance is recorded.
    /// @param id Invocation-local, nonzero identifier generated by the SDK.
    struct BalanceCheckpoint {
        address token;
        bytes32 id;
    }

    /// @notice Describes one ABI word to replace with a balance-derived amount.
    /// @dev The account validates selector-relative alignment, bounds, and ordering,
    ///      but cannot determine whether an aligned word is semantically an amount,
    ///      pointer, length, receiver, or another field. The SDK must derive offsets
    ///      from structured ABIs and verify them with golden calldata vectors.
    /// @param token ERC20 whose delegated-account balance determines the amount.
    /// @param checkpointId Zero for `CurrentBalance`; an earlier call's checkpoint ID for `CheckpointDelta`.
    ///        A checkpoint declared by the same `DynamicCall` is not yet visible and causes `CheckpointNotFound`.
    /// @param offset Byte offset from the start of `DynamicCall.data`, including its four-byte selector.
    /// @param bps Portion of the selected balance source, from 1 through 10,000 basis points.
    /// @param source Balance source used to calculate the replacement amount.
    struct BalancePatch {
        address token;
        bytes32 checkpointId;
        uint32 offset;
        uint16 bps;
        BalanceSource source;
    }

    /// @notice Describes one target call and its pre-call dynamic-balance operations.
    /// @param target Nonzero external target; the delegated account itself is forbidden.
    /// @param value Native value paid from the delegated account balance.
    /// @param data Target calldata copied to memory before patches are applied.
    /// @param checkpointsBefore Balance snapshots created after patches and immediately before the target call.
    /// @param patches Strictly offset-sorted calldata word replacements resolved before checkpoint creation.
    /// @param expectsCallback Whether this exact outer call must consume the single authenticated callback window.
    struct DynamicCall {
        address target;
        uint256 value;
        bytes data;
        BalanceCheckpoint[] checkpointsBefore;
        BalancePatch[] patches;
        bool expectsCallback;
    }

    /// @notice Carries the premium bound and dynamic plan executed inside an Aave V3 callback.
    /// @dev Every callback call must set `expectsCallback` to false in v1.
    /// @param maxPremium Maximum Aave V3 premium accepted for the flash loan.
    /// @param callbackCalls Ordered dynamic calls executed while the authenticated callback is active.
    struct CallbackEnvelope {
        uint256 maxPremium;
        DynamicCall[] callbackCalls;
    }

    /// @notice Raised when dynamic execution receives no calls.
    error EmptyDynamicBatch();

    /// @notice Raised when a dynamic execution reenters the same delegated account.
    error DynamicExecutionReentered();

    /// @notice Raised when a call targets the zero address or the delegated account itself.
    /// @param callIndex Index of the invalid call in the dynamic batch.
    /// @param target Invalid target address.
    error InvalidTarget(uint256 callIndex, address target);

    /// @notice Raised when a checkpoint specifies the zero token address.
    /// @param callIndex Index of the call declaring the checkpoint.
    /// @param checkpointIndex Index of the invalid checkpoint within the call.
    error InvalidCheckpointToken(uint256 callIndex, uint256 checkpointIndex);

    /// @notice Raised when a checkpoint specifies the zero identifier.
    /// @param callIndex Index of the call declaring the checkpoint.
    /// @param checkpointIndex Index of the invalid checkpoint within the call.
    error InvalidCheckpointId(uint256 callIndex, uint256 checkpointIndex);

    /// @notice Raised when a checkpoint identifier already exists in the active invocation.
    /// @param callIndex Index of the call declaring the duplicate checkpoint.
    /// @param checkpointIndex Index of the duplicate checkpoint within the call.
    /// @param id Duplicate checkpoint identifier.
    error CheckpointAlreadyExists(uint256 callIndex, uint256 checkpointIndex, bytes32 id);

    /// @notice Raised when a patch references a checkpoint absent from the active invocation.
    /// @param callIndex Index of the call containing the patch.
    /// @param patchIndex Index of the patch within the call.
    /// @param id Missing checkpoint identifier.
    error CheckpointNotFound(uint256 callIndex, uint256 patchIndex, bytes32 id);

    /// @notice Raised when a patch token differs from its referenced checkpoint token.
    /// @param callIndex Index of the call containing the patch.
    /// @param patchIndex Index of the patch within the call.
    /// @param id Referenced checkpoint identifier.
    /// @param expected Token requested by the patch.
    /// @param actual Token recorded by the checkpoint.
    error CheckpointTokenMismatch(uint256 callIndex, uint256 patchIndex, bytes32 id, address expected, address actual);

    /// @notice Raised when a patch specifies the zero token address.
    /// @param callIndex Index of the call containing the patch.
    /// @param patchIndex Index of the invalid patch within the call.
    error InvalidPatchToken(uint256 callIndex, uint256 patchIndex);

    /// @notice Raised when a patch offset is selector-overlapping, unaligned, or out of bounds.
    /// @param callIndex Index of the call containing the patch.
    /// @param patchIndex Index of the invalid patch within the call.
    /// @param offset Invalid byte offset.
    /// @param dataLength Length of the target calldata.
    error InvalidPatchOffset(uint256 callIndex, uint256 patchIndex, uint256 offset, uint256 dataLength);

    /// @notice Raised when patch offsets within one call are not strictly increasing.
    /// @param callIndex Index of the call containing the patch.
    /// @param patchIndex Index of the unsorted patch within the call.
    /// @param previous Previous patch offset.
    /// @param current Current patch offset.
    error UnsortedPatchOffset(uint256 callIndex, uint256 patchIndex, uint256 previous, uint256 current);

    /// @notice Raised when a patch percentage is outside 1 through 10,000 basis points.
    /// @param callIndex Index of the call containing the patch.
    /// @param patchIndex Index of the invalid patch within the call.
    /// @param bps Invalid basis-point value.
    error InvalidBps(uint256 callIndex, uint256 patchIndex, uint256 bps);

    /// @notice Raised when `CurrentBalance` is paired with a nonzero checkpoint identifier.
    /// @param callIndex Index of the call containing the patch.
    /// @param patchIndex Index of the invalid patch within the call.
    /// @param id Unexpected checkpoint identifier.
    error UnexpectedCheckpointId(uint256 callIndex, uint256 patchIndex, bytes32 id);

    /// @notice Raised when an ERC20 balance read triggered by checkpoint creation fails or returns fewer than 32 bytes.
    /// @param callIndex Index of the call declaring the checkpoint.
    /// @param checkpointIndex Index of the checkpoint that first triggered the read.
    /// @param token ERC20 whose balance read failed.
    /// @param reason Complete returndata from the failed or malformed balance read.
    error CheckpointBalanceReadFailed(uint256 callIndex, uint256 checkpointIndex, address token, bytes reason);

    /// @notice Raised when an ERC20 balance read triggered by patch resolution fails or returns fewer than 32 bytes.
    /// @param callIndex Index of the call containing the patch.
    /// @param patchIndex Index of the patch that first triggered the read.
    /// @param token ERC20 whose balance read failed.
    /// @param reason Complete returndata from the failed or malformed balance read.
    error PatchBalanceReadFailed(uint256 callIndex, uint256 patchIndex, address token, bytes reason);

    /// @notice Raised when a checkpoint-delta token balance decreased below its checkpoint.
    /// @param callIndex Index of the call containing the patch.
    /// @param patchIndex Index of the patch within the call.
    /// @param token ERC20 whose balance decreased.
    /// @param checkpointId Referenced checkpoint identifier.
    /// @param current Current delegated-account token balance.
    /// @param checkpoint Balance recorded at the checkpoint.
    error BalanceBelowCheckpoint(
        uint256 callIndex, uint256 patchIndex, address token, bytes32 checkpointId, uint256 current, uint256 checkpoint
    );

    /// @notice Raised when a dynamic target call fails.
    /// @param index Index of the failed call in the dynamic batch.
    /// @param target Target whose call failed.
    /// @param reason Complete target revert data.
    error DynamicCallFailed(uint256 index, address target, bytes reason);

    /// @notice Raised when more than one outer call requests a callback window.
    /// @param firstCallIndex Index of the first callback-enabled call.
    /// @param secondCallIndex Index of the next callback-enabled call.
    error MultipleExpectedCallbacks(uint256 firstCallIndex, uint256 secondCallIndex);

    /// @notice Raised when the callback receiver is called outside active dynamic execution.
    error CallbackOutsideDynamicExecution();

    /// @notice Raised when a callback arrives while its transient state is not awaiting consumption.
    /// @param callIndex Index of the callback-enabled outer call.
    /// @param actualState Actual callback-state ordinal.
    error CallbackNotAwaiting(uint256 callIndex, uint8 actualState);

    /// @notice Raised when a callback sender differs from the committed direct outer target.
    /// @param callIndex Index of the callback-enabled outer call.
    /// @param expected Committed direct outer target.
    /// @param actual Actual callback sender.
    error UnexpectedCallbackSender(uint256 callIndex, address expected, address actual);

    /// @notice Raised when Aave reports an initiator other than the delegated account.
    /// @param callIndex Index of the callback-enabled outer call.
    /// @param expected Delegated account required as the flash-loan initiator.
    /// @param actual Actual initiator supplied to the callback.
    error UnexpectedCallbackInitiator(uint256 callIndex, address expected, address actual);

    /// @notice Raised when reconstructed Aave calldata differs from the committed patched calldata.
    /// @param callIndex Index of the callback-enabled outer call.
    /// @param expected Committed hash of the patched outer calldata.
    /// @param actual Hash reconstructed from the callback arguments.
    error CallbackOriginMismatch(uint256 callIndex, bytes32 expected, bytes32 actual);

    /// @notice Raised when a callback-enabled target returns without exactly one consumed callback.
    /// @param callIndex Index of the callback-enabled outer call.
    /// @param target Direct outer target expected to call back.
    /// @param actualState Actual callback-state ordinal after the target returns.
    error CallbackNotConsumed(uint256 callIndex, address target, uint8 actualState);

    /// @notice Raised when a callback plan recursively requests another callback window.
    /// @param outerCallIndex Index of the callback-enabled outer call.
    /// @param callbackCallIndex Index of the invalid nested callback call.
    error NestedCallbackNotSupported(uint256 outerCallIndex, uint256 callbackCallIndex);

    /// @notice Raised when the Aave premium exceeds the signed plan's maximum.
    /// @param callIndex Index of the callback-enabled outer call.
    /// @param actual Premium reported by the Aave Pool.
    /// @param maximum Maximum premium accepted by the callback envelope.
    error FlashLoanPremiumTooHigh(uint256 callIndex, uint256 actual, uint256 maximum);

    /// @notice Raised when the delegated account cannot cover flash-loan principal plus premium.
    /// @param callIndex Index of the callback-enabled outer call.
    /// @param asset Flash-loaned ERC20 repayment asset.
    /// @param actual Actual delegated-account asset balance.
    /// @param required Principal-plus-premium repayment balance required.
    error FlashLoanRepaymentBalanceInsufficient(uint256 callIndex, address asset, uint256 actual, uint256 required);

    /// @notice Raised when installing the exact Aave Pool repayment allowance fails.
    /// @param callIndex Index of the callback-enabled outer call.
    /// @param asset Flash-loaned ERC20 repayment asset.
    /// @param pool Aave Pool receiving repayment authority.
    /// @param reason Complete failed approval returndata.
    error FlashLoanRepaymentApprovalFailed(uint256 callIndex, address asset, address pool, bytes reason);

    /// @notice Raised when reading the Pool's remaining repayment allowance fails or is malformed.
    /// @param callIndex Index of the callback-enabled outer call.
    /// @param asset Flash-loaned ERC20 repayment asset.
    /// @param pool Aave Pool whose allowance is read.
    /// @param reason Complete failed or malformed allowance returndata.
    error FlashLoanAllowanceReadFailed(uint256 callIndex, address asset, address pool, bytes reason);

    /// @notice Raised when the Pool leaves any repayment allowance after its outer call returns.
    /// @param callIndex Index of the callback-enabled outer call.
    /// @param asset Flash-loaned ERC20 repayment asset.
    /// @param pool Aave Pool retaining allowance.
    /// @param remaining Remaining nonzero allowance.
    error ResidualFlashLoanAllowance(uint256 callIndex, address asset, address pool, uint256 remaining);

    /// @notice Raised when a dynamic target call inside the authenticated callback fails.
    /// @param outerCallIndex Index of the callback-enabled outer call.
    /// @param callbackCallIndex Index of the failed call inside the callback envelope.
    /// @param target Callback-plan target whose call failed.
    /// @param reason Complete target revert data.
    error CallbackDynamicCallFailed(uint256 outerCallIndex, uint256 callbackCallIndex, address target, bytes reason);

    /// @notice Executes an authorized, atomic sequence of balance-patched external calls.
    /// @dev Each call resolves patches, creates checkpoints, and then executes its target in array order.
    ///      At most one outer call may request a callback; callback execution remains disabled until
    ///      the authenticated commitment engine is installed. Successful target returndata is discarded;
    ///      a failure reverts the entire batch.
    /// @param calls Ordered dynamic calls to execute from the delegated account.
    function executeBatchDynamic(DynamicCall[] calldata calls) external payable;

    /// @notice Receives the authenticated callback for one direct Aave V3 `flashLoanSimple` call.
    /// @dev This is not a user execution entrypoint. It authenticates an already-authorized outer
    ///      invocation and remains fail-closed until the callback commitment engine is installed.
    /// @param asset ERC20 asset supplied by the Aave V3 Pool.
    /// @param amount Flash-loan principal supplied by the Pool.
    /// @param premium Premium charged by the Pool.
    /// @param initiator Address that initiated the Aave flash loan.
    /// @param params ABI-encoded `CallbackEnvelope` committed by the outer call.
    /// @return success True only after the authenticated callback plan and exact repayment setup succeed.
    function executeOperation(address asset, uint256 amount, uint256 premium, address initiator, bytes calldata params)
        external
        returns (bool success);
}
