// SPDX-License-Identifier: MIT
pragma solidity 0.8.36;

/// @title IDefiSimplify7702Account
/// @notice Frozen v1 ABI for checkpoint-based dynamic account execution.
interface IDefiSimplify7702Account {
    /// @notice Selects the token-balance base used to resolve a calldata patch.
    enum BalanceSource {
        /// @notice Uses the delegated account's entire current token balance.
        CurrentBalance,
        /// @notice Uses only the balance increase since a named checkpoint.
        CheckpointDelta
    }

    /// @notice Describes an ERC20 balance snapshot created before a target call.
    /// @param token ERC20 whose delegated-account balance is recorded.
    /// @param id Invocation-local, nonzero identifier generated by the SDK.
    struct BalanceCheckpoint {
        address token;
        bytes32 id;
    }

    /// @notice Describes one ABI word to replace with a balance-derived amount.
    /// @param token ERC20 whose delegated-account balance determines the amount.
    /// @param checkpointId Zero for `CurrentBalance`; an earlier checkpoint ID for `CheckpointDelta`.
    /// @param offset Byte offset from the start of `DynamicCall.data`, including its four-byte selector.
    /// @param bps Portion of the selected balance source, from 1 through 10,000 basis points.
    /// @param source Balance source used to calculate the replacement amount.
    struct BalancePatch {
        address token;
        bytes32 checkpointId;
        uint32 offset;
        uint16 bps;
        BalanceSource source;
    }

    /// @notice Describes one target call and its pre-call dynamic-balance operations.
    /// @param target Nonzero external target; the delegated account itself is forbidden.
    /// @param value Native value paid from the delegated account balance.
    /// @param data Target calldata copied to memory before patches are applied.
    /// @param checkpointsBefore Balance snapshots created after patches and immediately before the target call.
    /// @param patches Strictly offset-sorted calldata word replacements resolved before checkpoint creation.
    struct DynamicCall {
        address target;
        uint256 value;
        bytes data;
        BalanceCheckpoint[] checkpointsBefore;
        BalancePatch[] patches;
    }

    /// @notice Raised when dynamic execution receives no calls.
    error EmptyDynamicBatch();

    /// @notice Raised when a dynamic execution reenters the same delegated account.
    error DynamicExecutionReentered();

    /// @notice Raised when a call targets the zero address or the delegated account itself.
    /// @param callIndex Index of the invalid call in the dynamic batch.
    /// @param target Invalid target address.
    error InvalidTarget(uint256 callIndex, address target);

    /// @notice Raised when a checkpoint specifies the zero token address.
    /// @param callIndex Index of the call declaring the checkpoint.
    /// @param checkpointIndex Index of the invalid checkpoint within the call.
    error InvalidCheckpointToken(uint256 callIndex, uint256 checkpointIndex);

    /// @notice Raised when a checkpoint specifies the zero identifier.
    /// @param callIndex Index of the call declaring the checkpoint.
    /// @param checkpointIndex Index of the invalid checkpoint within the call.
    error InvalidCheckpointId(uint256 callIndex, uint256 checkpointIndex);

    /// @notice Raised when a checkpoint identifier already exists in the active invocation.
    /// @param callIndex Index of the call declaring the duplicate checkpoint.
    /// @param checkpointIndex Index of the duplicate checkpoint within the call.
    /// @param id Duplicate checkpoint identifier.
    error CheckpointAlreadyExists(uint256 callIndex, uint256 checkpointIndex, bytes32 id);

    /// @notice Raised when a patch references a checkpoint absent from the active invocation.
    /// @param callIndex Index of the call containing the patch.
    /// @param patchIndex Index of the patch within the call.
    /// @param id Missing checkpoint identifier.
    error CheckpointNotFound(uint256 callIndex, uint256 patchIndex, bytes32 id);

    /// @notice Raised when a patch token differs from its referenced checkpoint token.
    /// @param callIndex Index of the call containing the patch.
    /// @param patchIndex Index of the patch within the call.
    /// @param id Referenced checkpoint identifier.
    /// @param expected Token requested by the patch.
    /// @param actual Token recorded by the checkpoint.
    error CheckpointTokenMismatch(uint256 callIndex, uint256 patchIndex, bytes32 id, address expected, address actual);

    /// @notice Raised when a patch specifies the zero token address.
    /// @param callIndex Index of the call containing the patch.
    /// @param patchIndex Index of the invalid patch within the call.
    error InvalidPatchToken(uint256 callIndex, uint256 patchIndex);

    /// @notice Raised when a patch offset is selector-overlapping, unaligned, or out of bounds.
    /// @param callIndex Index of the call containing the patch.
    /// @param patchIndex Index of the invalid patch within the call.
    /// @param offset Invalid byte offset.
    /// @param dataLength Length of the target calldata.
    error InvalidPatchOffset(uint256 callIndex, uint256 patchIndex, uint256 offset, uint256 dataLength);

    /// @notice Raised when patch offsets within one call are not strictly increasing.
    /// @param callIndex Index of the call containing the patch.
    /// @param patchIndex Index of the unsorted patch within the call.
    /// @param previous Previous patch offset.
    /// @param current Current patch offset.
    error UnsortedPatchOffset(uint256 callIndex, uint256 patchIndex, uint256 previous, uint256 current);

    /// @notice Raised when a patch percentage is outside 1 through 10,000 basis points.
    /// @param callIndex Index of the call containing the patch.
    /// @param patchIndex Index of the invalid patch within the call.
    /// @param bps Invalid basis-point value.
    error InvalidBps(uint256 callIndex, uint256 patchIndex, uint256 bps);

    /// @notice Raised when `CurrentBalance` is paired with a nonzero checkpoint identifier.
    /// @param callIndex Index of the call containing the patch.
    /// @param patchIndex Index of the invalid patch within the call.
    /// @param id Unexpected checkpoint identifier.
    error UnexpectedCheckpointId(uint256 callIndex, uint256 patchIndex, bytes32 id);

    /// @notice Raised when an ERC20 balance read triggered by checkpoint creation fails or returns fewer than 32 bytes.
    /// @param callIndex Index of the call declaring the checkpoint.
    /// @param checkpointIndex Index of the checkpoint that first triggered the read.
    /// @param token ERC20 whose balance read failed.
    /// @param reason Complete returndata from the failed or malformed balance read.
    error CheckpointBalanceReadFailed(uint256 callIndex, uint256 checkpointIndex, address token, bytes reason);

    /// @notice Raised when an ERC20 balance read triggered by patch resolution fails or returns fewer than 32 bytes.
    /// @param callIndex Index of the call containing the patch.
    /// @param patchIndex Index of the patch that first triggered the read.
    /// @param token ERC20 whose balance read failed.
    /// @param reason Complete returndata from the failed or malformed balance read.
    error PatchBalanceReadFailed(uint256 callIndex, uint256 patchIndex, address token, bytes reason);

    /// @notice Raised when a checkpoint-delta token balance decreased below its checkpoint.
    /// @param callIndex Index of the call containing the patch.
    /// @param patchIndex Index of the patch within the call.
    /// @param token ERC20 whose balance decreased.
    /// @param checkpointId Referenced checkpoint identifier.
    /// @param current Current delegated-account token balance.
    /// @param checkpoint Balance recorded at the checkpoint.
    error BalanceBelowCheckpoint(
        uint256 callIndex, uint256 patchIndex, address token, bytes32 checkpointId, uint256 current, uint256 checkpoint
    );

    /// @notice Raised when a dynamic target call fails.
    /// @param index Index of the failed call in the dynamic batch.
    /// @param target Target whose call failed.
    /// @param reason Complete target revert data.
    error DynamicCallFailed(uint256 index, address target, bytes reason);

    /// @notice Executes an authorized, atomic sequence of balance-patched external calls.
    /// @dev Each call resolves patches, creates checkpoints, and then executes its target in array order.
    ///      Successful target returndata is discarded; a failure reverts the entire batch.
    /// @param calls Ordered dynamic calls to execute from the delegated account.
    function executeBatchDynamic(DynamicCall[] calldata calls) external payable;
}
